package model;

public interface Query {
	
	String INSERT_GUEST_QUERY="INSERT INTO GUEST" +
			" (GUESTID," +
			"GUESTNAME," +
			"GUESTADDRESS," +
			"GUESTAFFILIATION)" +
			" VALUES (seq_guest.nextval,?,?,?)";
	
	String CITY_TYPE_DATE="SELECT H.HOTELID,H.HOTELNAME,H.CITY,R.ROOMNO,R.PRICE FROM ROOM R,HOTEL H WHERE H.HOTELID=R.HOTELID AND H.CITY=? AND R.ROOMTYPE=? AND (H.HOTELNAME,R.ROOMNO) NOT IN(SELECT HO.HOTELNAME,B.ROOMNO FROM BOOKING B,HOTEL HO WHERE B.HOTELID=HO.HOTELID AND ((B.STARTDATE = to_date (?, 'YYYY-MM-DD') AND B.ENDDATE = to_date (?, 'YYYY-MM-DD')) OR (B.STARTDATE > to_date (?, 'YYYY-MM-DD') AND B.STARTDATE < to_date (?, 'YYYY-MM-DD')) OR (B.ENDDATE > to_date (?, 'YYYY-MM-DD') AND B.ENDDATE < to_date (?, 'YYYY-MM-DD')) OR (B.STARTDATE < to_date (?, 'YYYY-MM-DD') AND B.ENDDATE > to_date (?, 'YYYY-MM-DD')) OR (B.STARTDATE > to_date (?, 'YYYY-MM-DD') AND B.ENDDATE < to_date (?, 'YYYY-MM-DD'))))";
	
	String INSERT_BOOK_ROOM="INSERT INTO BOOKING" +
	        " (HOTELID, ROOMNO, GUESTID, STARTDATE, ENDDATE)"+
			" VALUES (?,?,?,to_date (?, 'YYYY-MM-DD'),to_date (?, 'YYYY-MM-DD'))";
	
	String INSERT_BOOK_ROOM_REFERENCE="INSERT INTO BOOKINGREFERENCE" +
	        "(BOOKINGID, HOTELID, ROOMNO, GUESTID, STARTDATE, ENDDATE)" +
			"VALUES (seq_booking.nextval, ?, ?, ?,to_date (?, 'YYYY-MM-DD'), to_date (?, 'YYYY-MM-DD'))";
	
	String CUSTOMER_ID="SELECT BOOKINGID FROM BOOKINGREFERENCE WHERE HOTELID=? AND ROOMNO=? AND GUESTID=? AND STARTDATE=to_date (?, 'YYYY-MM-DD') AND ENDDATE=to_date (?, 'YYYY-MM-DD')";
	
	String GUEST_SEARCH_QUERY="SELECT GUESTID, GUESTNAME, GUESTADDRESS, GUESTAFFILIATION FROM GUEST WHERE GUESTNAME = ?";
}